force-app/main/default/objects/API__c/API__c.object-meta.xml
<CustomObject>
    <label>API</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API__c/fields/HTTP_Content_Type__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Content_Type__c</fullName>
    <label>HTTP Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/API_OpenMeteo.cls
public class API_OpenMeteo {
    public static void getWeather(API__c api, ID  objectId){
        List<String> errorList = new List<String>();
        Map<String, Object> response = new Map<String, Object>();
        
        List<Account> accList = [SELECT ID, Name, Description
                                 FROM Account WHERE ID = :objectId LIMIT 1];
        if (accList.size() < 1){
            errorList.add('No Account.');
            API_Framework.logAPIRequest(api.id, '- no data -', '-0', 'No Account.', 'Open', 'API_OpenMEteo', (String)objectId, '-no data-');
        }
        else{
            Account acc = accList.get(0);
            
        	response = API_Framework.outboundRestCall(api.Id, api.Credential__c, api.HTTP_Method__c, api.HTTP_Content_Type__c, null);
            system.debug(response);
            
            Decimal input = (Decimal)response.get('elevation');
            String temperature = (String)response.get('temperature_2m');
            acc.Description = 'Elevation: ' + String.valueOf(input) + '\nTemperature: ' + temperature;
            
            upsert acc;
            
        }
    }
}