force-app/main/default/objects/API__c/API__c.object-meta.xml
<CustomObject>
    <label>API</label>
    <nameField>
        <label>API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Apex Class</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API__c/fields/HTTP_Content_Type__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Content_Type__c</fullName>
    <label>HTTP Content Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API__c/recordTypes/Outbound.recordType-meta.xml
<RecordType>
    <fullName>Outbound</fullName>
    <active>true</active>
    <label>Outbound</label>
</RecordType>

force-app/main/default/objects/Log_API__c/Log_API__c.object-meta.xml
<CustomObject>
    <label>Log API</label>
    <nameField>
        <displayFormat>LOGAPI{000000}</displayFormat>
        <label>Log API Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs API</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_API__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <label>API</label>
    <referenceTo>API__c</referenceTo>
    <relationshipLabel>Log API</relationshipLabel>
    <relationshipName>Log_API</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Log_API__c/fields/API_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Record_Type__c</fullName>
    <label>API Record Type</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_API__c/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_API__c/fields/Input_Body__c.field-meta.xml
<CustomField>
    <fullName>Input_Body__c</fullName>
    <label>Input Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_API__c/fields/Output_Body__c.field-meta.xml
<CustomField>
    <fullName>Output_Body__c</fullName>
    <label>Output Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/API_Framework.cls
public without sharing class API_Framework {
    
    // Call API
    //
    // Hub to select which API class to work with
    // Values:
    // 
    // List<List<String>> idList - list with API id and Object id. List<List<>> for workflow compability.
    // 
    // Returns:
    // 
    // List<List<String>> with errors that occurred during the call of this class. List<List<>> for workflow compability.
    //
    @InvocableMethod
    public static List<List<String>> callApi(List<List<String>> idList){
        List<List<String>> returnList = new List<List<String>>();
        List<String> errorList = new List<String>();
        String queryString = '';
        
        List<String> queryId = idList.get(0);
        String apiId = queryId.get(0);
        String objectId = queryId.get(1);
        
        List<API__c> apiList = [SELECT Id, Name, Object_Name__c, Credential__c, HTTP_Method__c, HTTP_Content_Type__c
                                FROM API__c WHERE Id = :apiId LIMIT 1];
        
        if (apiList.size() < 1){
            errorList.add('No API.');
            logAPIRequest(queryId.get(0), '- no data -', '-0', 'No API.', 'Open', 'API_Framework', '-no data-', '-no data-');
        }
        else{
            API__c api = apiList[0];
            
            switch on api.Name {
                when 'Open-Meteo' {
                    API_OpenMeteo.getWeather(api, objectId);
                }	
                when 'Jokes' {
                    //call method
                }
                when 'CoinDesk' {
                    //call method
                }
                when else {
                    errorList.add('No API method implemented.');
                    logAPIRequest(api.Id, '- no data -', '-0', 'No API method implemented.', 'Open', 'API_Framework', '-no data-', api.HTTP_Method__c);
                }
            }
            
            if(errorList.isEmpty() != TRUE){
                returnList.add(errorList);
            }
            else{
                returnList = null;
            }
        }
        
        return returnList;
        
    }
    
    // Outbound Rest Call to API
    //
    // Make a call to send/get data from the API 
    // Values:
    // 
    // Id apiId - ID of the API called
    // String credential - Named credential used by the API
    // String method - HTTP method used
    // String contentType - content type defiened by the API 
    // String body - body used to send data to the API.
    // 
    // Returns:
    // 
    // Map<String, Object> with information from the response from the API
    //
    public static Map<String, Object> outboundRestCall(Id apiId, String credential, String method, String contentType, String body){
        Map<String, Object> responseList = new Map<String, Object>();
        
        try{
            Http httpInstance = new Http();
            HttpRequest request = new HttpRequest();
            HttpResponse response;
            
            String endpoint = 'callout:' + credential;
            
            request.setEndpoint(endpoint);
            
            request.setMethod(method);
            request.setHeader('Content-Type', contentType);
            if(method == 'POST' || method == 'PUT'){
                request.setBody(body);
            }
            
            response = httpInstance.send(request);
            
            if (response.getStatusCode() == 201 || response.getStatusCode() == 200) {
                responseList = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
				
                //temp
                logAPIRequest(apiId, String.valueOf(request), String.valueOf(response.getStatusCode()), response.getBody(), 'Closed', 'API_Framework', 'id : ', method);
            }
            else {
                responseList = null;
                
                // Handle the error
                logAPIRequest(apiId, String.valueOf(request), String.valueOf(response.getStatusCode()), response.getBody(), 'Open', 'API_Framework', 'id : ', method);
            }
        } catch (DmlException e) {
            responseList = null;
            
            logAPIRequest(apiId, '', '-5', e.getMessage(), 'Open', 'API_Framework', 'id : ', method);
        }
        
        return responseList;
    }
    
    // Log API Request
    // 
    // Create a Log_API object, that shows the values of a error or a call to the API.
    // Values:
    // 
    // ID apiId - ID of the API called
    // String inputMsg - Message/Body sent to the API 
    // String retCode - code received (ex. 201, 430, 500, ...)
    // String outputMsg - Message/Body received from the API 
    // String status - values: Closed - no error in the call | Open - error during the call
    // String apexClass - Apex class where this method was called
    // String objectID - ID of the object that was being handled in the call
    // String httpMethod - HTTP method used
    //
    public static void logAPIRequest(Id apiId, String inputMsg, String retCode, String outputMsg, String status, String apexClass, String objectId, String httpMethod){
        Log_API__c log = new Log_API__c();
        
        List<API__c> apiList = [SELECT Id, Name, Credential__c, HTTP_Method__c, HTTP_Content_Type__c, RecordType.Name
                                FROM API__c WHERE Id = :apiId LIMIT 1];
        
        if (apiList.size() == 1){
            API__c api = apiList[0];
            log.API_Record_Type__c = api.RecordType.Name;
        }
        
        log.API__C = apiId;
        log.Input_Body__c = inputMsg;
        log.Return_Code__c = retCode;
        log.Output_Body__c = outputMsg;
        log.Status__c = status;
        log.Apex_Class__c = apexClass;
        log.Object_ID__c = objectId;
        log.HTTP_Method__c = httpMethod;
        
        insert log;
    }
    
}